# Generated by Django 5.2.3 on 2025-09-19 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('image__isnull', False), ('video__isnull', False), models.Q(('image', ''), _negated=True), models.Q(('video', ''), _negated=True), _negated=True), name='only_one_media_type'),
        ),
    ]
