# Generated by Django 5.2.3 on 2025-10-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_is_blocked_by_system_post_is_offensive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
