# Generated by Django 5.2.3 on 2025-10-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_is_nsfw'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_to_speech_file',
            field=models.FileField(blank=True, null=True, upload_to='text_to_speech/'),
        ),
    ]
