# Generated by Django 5.2.3 on 2025-09-23 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_follow_no_self_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['target', 'created_at'], name='follows_fol_target__2218f6_idx'),
        ),
    ]
